apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # highlight-next-line
        eks.tke.cloud.tencent.com/spread-placement-group-id: ps-xxxxxxxx
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: eklet
      containers:
        - name: nginx
          image: nginx:latest
