apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      # highlight-start
      annotations:
        eks.tke.cloud.tencent.com/cpu-type: "SA5,SA4,amd" # 优先使用 SA5，如果没资源就尝试 SA4，如果都没有再尝试其他所有 AMD 系列 CPU 的机型
      # highlight-end
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: eklet
      containers:
        - name: nginx
          image: nginx:latest
