apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # highlight-start
        tke.cloud.tencent.com/networks: "tke-route-eni" # 如果集群网络是 GlobalRouter + VPC-CNI 混用，用此注解需要显式指定 Pod 使用 VPC-CNI
        # 指定 EIP 属性，具体字段参考 CLB 的 AllocateAddresses 接口文档：https://cloud.tencent.com/document/api/215/16699#2.-.E8.BE.93.E5.85.A5.E5.8F.82.E6.95.B0
        tke.cloud.tencent.com/eip-attributes: '{"Bandwidth":"100", "ISP":"BGP", "InternetMaxBandwidthOut":50, "InternetChargeType":"TRAFFIC_POSTPAID_BY_HOUR"}'
        # highlight-end
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: eklet
      containers:
        - name: nginx
          image: nginx:latest
          # highlight-start
          resources: # 声明 EIP 资源，用于调度 (节点能绑定的 EIP 数量有限)
            limits:
              tke.cloud.tencent.com/eni-ip: "1"
              tke.cloud.tencent.com/eip: "1"
            requests:
              tke.cloud.tencent.com/eni-ip: "1"
              tke.cloud.tencent.com/eip: "1"
          # highlight-end
          command:
            - sleep
            - infinity
          # highlight-start
          volumeMounts:
            - mountPath: /etc/podinfo # 容器内读取 /etc/podinfo/eip 可获取当前 Pod EIP 信息
              name: podinfo
          # highlight-end
      volumes:
        # highlight-start
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "eip" # 关键
                fieldRef:
                  fieldPath: metadata.annotations['tke.cloud.tencent.com/eip-public-ip']
        # highlight-end
