apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sglang
spec:
  selector:
    matchLabels:
      app: sglang
  serviceName: sglang
  replicas: 2
  template:
    metadata:
      labels:
        app: sglang
    spec:
      containers:
      - name: sglang
        image: lmsysorg/sglang:latest
        env:
        - name: LLM_MODEL
          value: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
        - name: TOTAL_GPU
          value: "8"
        - name: REPLICAS
          value: "2"
        - name: STATEFULSET_NAME
          value: "sglang"
        - name: SERVICE_NAME
          value: "sglang"
        - name: ORDINAL_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        ports:
        - containerPort: 30000
        resources:
          limits:
            nvidia.com/gpu: "4"
        command:
        - bash
        - -c
        - |
          if [[ "$ORDINAL_NUMBER" == "0" ]]; then
            python3 -m sglang.launch_server --model-path /data/$LLM_MODEL --tp $TOTAL_GPU --dist-init-addr $STATEFULSET_NAME-0.$SERVICE_NAME:5000 --nnodes $REPLICAS --node-rank $ORDINAL_NUMBER --trust-remote-code --host 0.0.0.0 --port 30000
          else
            python3 -m sglang.launch_server --model-path /data/$LLM_MODEL --tp $TOTAL_GPU --dist-init-addr $STATEFULSET_NAME-0.$SERVICE_NAME:5000 --nnodes $REPLICAS --node-rank $ORDINAL_NUMBER --trust-remote-code
          fi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ai-model
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 40Gi
---

apiVersion: v1
kind: Service
metadata:
  name: sglang
spec:
  selector:
    app: sglang
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    protocol: TCP
    port: 30000
    targetPort: 30000
