ports:
  web:
    expose:
      default: true
      # highlight-add-line
      ipv6: true
  websecure:
    expose:
      default: true
      # highlight-add-line
      ipv6: true
service:
  # highlight-add-start
  additionalServices:
    ipv6:
      type: LoadBalancer
      annotations:
        service.kubernetes.io/service.extensiveParameters: '{"AddressIPVersion":"IPv6FullChain"}'
  # highlight-add-end
