ports:
  web:
    expose:
      default: true
      # highlight-add-line
      internal: true
  websecure:
    expose:
      default: true
      # highlight-add-line
      internal: true
service:
  # highlight-add-start
  additionalServices:
    internal:
      type: LoadBalancer
      annotations:
        service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: "subnet-xxxxxxxx" # 配置内网 CLB 的子网
  # highlight-add-end
